Fix for "NoMethodError - undefined method `[]=' for nil:NilClass": when no parameters are used, the 'params' var reaches run_optional_rule as {}. Then when a namespace is found, an inner hash for the namespace can't be autovivified. This fix simply checks to see if the inner hash for the namespace already exists and if not creates an empty one.